### ISSUE TITLE
Security overview not availible

### ISSUE THREAD

**Issue by timostrating** [minvws/nl-covid19-coronacheck-app-android#12]
The corona Melder app from the RIVM uses the Google Exposier API. This API has been reviewed my multiple security experts. This app the CoronaCheck app looks to be using a custom designed flow. So I would like to see a breakdown of all security measures and a technical flow of the data and key exchanges that are going on.

So far I got the following information from searching the source code:

* (All) data transfer is encrypted using 2048 bit ssl keys. (The example key has 2048 bit, so the production key has probably the same)

* This site has an overview of the flow https://api-ct.bananenhalen.nl/overview/run/

So my question is if an overview can be made where all technical details are also shown.

**Comment by nicktencate** [comment]
There is a security document awaiting publication approval that will specify and explain all security measures. Once this is out, I will copy a link here.

**Comment by nicktencate** [comment]
Full documentation has been published here: https://github.com/minvws/nl-covid19-coronacheck-app-coordination
