### ISSUE TITLE
SSL certificate pinning

### ISSUE THREAD

**Issue by tapemaster** [minvws/nl-covid19-coronacheck-app-android#13]
While inspecting the code, I've found https://github.com/minvws/nl-covid19-coronacheck-app-android/blob/main/api/src/main/java/nl/rijksoverheid/ctr/api/interceptors/SignedResponseInterceptor.kt

Which checks signature of the response body. Are you guys planning to use the standard SSL certificate pinning instead of this custom solution?

**Comment by dirkx** [comment]
You probably want to have a look at this document: https://github.com/minvws/nl-covid19-coronacheck-app-coordination/blob/main/architecture/x509-pinning-1.07.pdf - and if you see something that is not correct in the code (i.e. we're not checking the pinning) - then do file a bug !

**Comment by ijansch** [comment]
Notably its not a custom solution ‘instead of’, it’s ‘in addition to’. Pinning validates the connection on network level, the cms signature checks the content integrity and origin.
