### ISSUE TITLE
Use android keystore to persist sensitive data

### ISSUE THREAD

**Issue by tapemaster** [minvws/nl-covid19-coronacheck-app-android#14]
While inspecting the code, I've found that we store CREDENTIALS and SECRET_KEY_JSON data in plaintext right into SharedPreferences. Are there plans to use android keystore for those?

https://github.com/minvws/nl-covid19-coronacheck-app-android/blob/main/holder/src/main/java/nl/rijksoverheid/ctr/holder/persistence/PersistenceManager.kt

**Comment by BartNijland91** [comment]
This is fixed in our private repo by using the `EncryptedSharedPreferences`. Will be visible once we sync the private to public again.
