### ISSUE TITLE
Scanner app does not show 4 letter/numbers to verify identity of citizen

### ISSUE THREAD

**Issue by mexiscool** [minvws/nl-covid19-coronacheck-app-android#19]
### Describe the bug, issue or concern
qr code scanned with cornacheck scanner app says qr code is valid but does display 4 underscores instead of the information to confirm the identity. This might not be a specific issue with the app but is concerning.

### To Reproduce
1. Go to Lead Healthcare for a corona test.
2. validate negative result in CoronaCheck app and show qr code.
3. Scan qr code on another device with the scanner app.

### Expected behavior
get 4 letters/numbers to verify identity 

### Screenshots
![image](https://user-images.githubusercontent.com/27775925/115078407-defe7800-9eff-11eb-8bd2-2021679193a9.png)

**Smartphone (please complete the following information):**
 - Device: both Samsung a71
 - OS: Android 11

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by BartNijland91** [comment]
This is intended behaviour as we are not allowed to show personal information yet.
