### ISSUE TITLE
Privacy Concerns

### ISSUE THREAD

**Issue by Mushoz** [minvws/nl-covid19-coronacheck-app-android#26]
### Describe the bug, issue or concern
Please do not get me wrong. I applaud the fact this application is open source and the fact privacy seems to be taken seriously while developing this application. Having said that, despite these considerations I am strongly against the sharing of ANY patient data, including vaccination status. While the generation of the QR code that is used within The Netherlands itself is much better  since it only shows a binary YES/NO without any additional details (such as what generated the YES: Negative test, recent infection or vaccinated), the European QR code that is supported within the application is a privacy disaster, showing things such as batch number of vaccination, number of shots and date at which the shots were received.

I have searched far and wide if this entire ecosystem can be opted out of. While I know it is possible to opt-out of sharing your vaccination information with the RIVM, as far as I know this application can also retrieve vaccination details from the GGD. I am strongly against this, and this fact has made me doubt whether I even want to be vaccinated in the first place. This feels extremely bad because I WANT to be vaccinated and be part of the solution of this crisis. However, my privacy concerns are currently preventing me from being that.

These questions aren't really related to the application itself, but since I was unable to find ANY relevant information on the topic, and since you guys have experience with retrieving the information from said systems, I was hoping the knowledge I am after can be found here. My questions:
1. As far as I know, if I get vaccinated at the GGD and choose to NOT share my details with the RIVM, the CoronaCheck app will still be able to generate the QR-codes that would allow me to attend an event. Is this correct?
2. Is there ANY way to opt out of this completely and make my vaccination status irretrievable by the CoronaCheck application? Yes, I know I would not be allowed into an event despite me being vaccinated if these details cannot be retrieved. However, I am completely fine with that.

Thank you very much in advance!

### Governance
- [X] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [X] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [X] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by Mushoz** [comment]
Antwoorden mogen ook in het Nederlands trouwens, mocht dat makkelijker zijn :)

**Comment by Derkades** [comment]
Punt 1 is mogelijk of gaat mogelijk worden: https://www.rtlnieuws.nl/nieuws/nederland/artikel/5233972/vaccinatie-rivm-niet-gedeeld-vaccinatiebewijs-vaccinatiepaspoort

Voor punt 2, voor zover ik weet haalt de app geen "vaccinatiestatus" op maar verifieert het eenmalig met een ggd (?) code om een digitale handtekening te creeren samen met een aantal niet-unieke persoonlijke gegevens (eerste letter van namen, geboortejaar zonder datum of geboortedatum zonder jaar (?)). De handtekening wordt gepresenteerd als een QR code maar zit los van de app, hij zou prima uitgeprint kunnen worden en dergelijke. De persoon die de QR code verifieert controleert dmv de app of de handtekening geldig is en kijkt naar je paspoort of de voorletters enzo kloppen (maar dit gaat handmatig, de app ziet deze gegevens nooit)
(dit is informatie die ik van verschillende bronnen heb gehoord de afgelopen tijd, ik kan het mis hebben)

**Comment by Mushoz** [comment]
Punt 1: Daar was ik inderdaad al bang voor. Dus ook als je niet je gegevens wil delen met het RIVM, kom je toch in systemen terecht waar CoronaCheck toegang tot heeft. Ik heb hiervan ook inmiddels bevestiging van gezien, van een persoon die ik ken en die gevaccineerd is, die zijn vaccinatie status rechtstreeks van de GGD in de CoronaCheck applicatie kreeg. De app gaf netjes weer dat de GGD de bron van de informatie was.

Punt 2: De QR code met een simpel Groen vinkje dan wel Rood vinkje is dus de QR code die intern in Nederland gebruikt wordt, die privacy technisch gezien een stuk beter in elkaar zit. Echter heeft de nieuwste CoronaCheck app ook de mogelijkheid om QR codes te genereren die binnen heel Europa geldig zijn. Deze bevatten een stuk meer informatie. Lijst van de dingen die in de QR code zitten:

- Date of birth
- Family name
- Given name
- Certificate
- Country of vaccination
- Number of doses received
- Date of vaccination
- Certificate issuer
- Vaccine manufacturer
- Vaccin product id
- Total number of doses
- Targetted disease (deze variabele is altijd "Covid-19", maar het bestaan van deze variabele impliceert dat dit systeem in de toekomst ook voor andere ziektes / vaccins gebruikt kan worden.
- Vaccin or prophylaxis
- Schema version
- QR code issuer
- QR code expiry
- QR code generated

Bron: https://tweakers.net/reviews/9166/het-digitale-coronapaspoort-hoe-de-app-om-te-kunnen-reizen-werkt.html
https://github.com/ehn-dcc-development/hcert-spec/releases/download/1.0.5/dgc_spec-1.0.5-final.pdf

En nou is het natuurlijk makkelijk om te zeggen: Je kunt ervoor kiezen om de QR code niet op te halen. Maar dat doet natuurlijk niks af aan het feit dat deze gegevens wél beschikbaar zijn in deze systemen, anders zou het namelijk onmogelijk zijn om deze uberhaupt op te halen. Ik ben zelf fel op tegen dat medische gegevens zomaar beschikbaar zijn en zó makkelijk op te halen zijn door externe applicaties. Ik wil heel graag mijn steentje bijdragen en gevaccineerd worden, maar niet als de privacy zo ten grabbel wordt gegooid.

**Comment by JJdeGroot** [comment]
Disclaimer: ik werk niet aan dit gedeelte van de app en dit is mijn persoonlijke mening.

De medische gegevens zijn toch niet zomaar beschikbaar? En ook niet heel makkelijk op te halen. Je zult eerst in moeten loggen met DigiD. Het lijkt me toch niet gek dat je dan bij je persoonlijke (medische) gegevens kan? Je kan via DigiD immers ook belastingaangifte doen, (medische) afspraken maken, berichtenbox berichten te lezen, medische dossier van huisarts bekijken, enz.

En via https://mijn.rivm.nl/vaccinaties/login kan je je vaccinaties bijvoorbeeld ook inzien.

Jouw medische gegevens worden niet zonder toestemming gedeeld. Door in te loggen met DigiD geef je toestemming om namens jou de gegevens uit de systemen te halen.

Er is geen centrale database waar alle gegevens uit de systemen van de RIVM en GGD verzameld zijn. Namens jou worden er een API calls gedaan naar de externe systemen om jouw persoonlijke QR te kunnen maken. En dit alles met zo min mogelijke gevoelige data.

Als je de app niet gebruikt, zullen je gegevens niet aangeraakt worden.

Waar het jou om gaat is dat het überhaupt mogelijk is om dit soort gegevens op te vragen uit systemen van het RIVM en de GGD?

Hoe het verder zit met de opt-out bij RIVM / GGD is bij mij niet bekend.

**Comment by Mushoz** [comment]
Bedankt voor je uitgebreide reactie!

> Waar het jou om gaat is dat het überhaupt mogelijk is om dit soort gegevens op te vragen uit systemen van het RIVM en de GGD?

Dat is precies mijn punt inderdaad. Als ik de app niet gebruikt zullen de gegevens niet opgevraagd worden uit deze systemen, dat klopt. Maar de gegevens zullen nog steeds wél in deze systemen opgeslagen zijn. Een datalek zou betekenen dat mijn vaccinatie gegevens op straat zouden komen te liggen. Wat ik probeer te achterhalen is of dat het mogelijk is om een vaccinatie ergens te halen zonder dat dit in systemen terecht komt die door CoronaCheck via API calls te benaderen is. Want het feit dat deze benaderbaar zijn door applicaties zoals CoronaCheck betekent dat dit op een server moet staan die verbonden is met het internet. Dit soort machines zullen altijd data breach risico's met zich meebrengen.

Het klopt dat er al veel informatie op te halen is via DigID. Maar dat betekent voor mij persoonlijk niet dat het dan maar meteen okay is om hier maar meer aan toe te voegen, behalve als daar echt een hele goede reden voor is. Als ik het goed begrijp is DigID slechts een authenticatie service. Doordat nu vaccinatie gegevens bij de GGD staan en toegankelijk zijn via DigID, betekent dus dat er weer een extra systeem is waar een datalek kan ontstaan waarbij mijn persoonlijke gegevens op straat zouden kunnen komen te liggen.

Mijn persoonlijke uitgangspunt is om zoveel mogelijk aan gegevens minimalisatie te doen. Vandaar dat ik me dus enorm stoor aan het feit dat er geen opt-out mogelijkheid is om wél een vaccinatie te halen maar níet deze gegevens toegankelijk te maken via DigID. Ik realiseer me dat dit niet heel erg ontopic is voor de CoronaCheck app zelf. Maar ik hoop dat hier mensen zijn die weten hoe het precies in elkaar zit en wat de mogelijkheden zijn, aangezien zij ervaring hebben met de communicatie met de verschillende systemen waarin je vaccinatie status geregistreerd word.

**Comment by ijansch** [comment]
We halen de gegevens vanuit de app rechtstreeks bij de bron. Er is dus geen coronacheck server die de data opslaat of ophaalt. Na je digid inlog haalt de app deze gegevens op bij de bron. Daarvoor moet die bron inderdaad de data via een publiek te benaderen endpoint ter beschikking stellen. Dit endpoint is beveiligd met een jwt token. Dat token moet ondertekend zijn met een door de authenticatie server gezette handtekening. 

De partijen bepalen zelf hoe ze dit endpoint bouwen; wij adviseren wel om dat te doen op een manier die niet meer data kan leveren dan voor het bewijs noodzakelijk. Met alle partijen worden wel afspraken gemaakt over de beveiliging. 

Of een partij wel of niet de optie biedt om je gegevens selectief beschikbaar te maken, dat is aan die partij. Dat kun je dan ook het beste daar navragen. 

De verordening van de Dcc vereist overigens dat partijen hun data ter beschikking stellen, maar zegt, zover ik weet, niets over het omgekeerde.
