### ISSUE TITLE
Does use Chrome instead of default browser?

### ISSUE THREAD

**Issue by richardhinkamp** [minvws/nl-covid19-coronacheck-app-android#27]
When try to login with DigiD, a URL (https://tvs.coronacheck.nl/authorize?....) is opened in Chrome which is not my default browser. I would expect it to open my default browser.

 - Device: Samsung Galaxy S10
 - OS: Android 11
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by JJdeGroot** [comment]
Which browser is your default browser?

We use the [OpenAuth library](https://github.com/openid/AppAuth-Android) with  [VersionedBrowserMatcher](https://github.com/openid/AppAuth-Android/blob/master/library/java/net/openid/appauth/browser/VersionedBrowserMatcher.java).

Chrome, Samsung, and FireFox browsers are all enabled for the CoronaCheck app.

**Comment by richardhinkamp** [comment]
[FireFox Focus](https://play.google.com/store/apps/details?id=org.mozilla.focus&hl=en_US&gl=US)

**Comment by JJdeGroot** [comment]
Thanks, I have passed it to the team to check if we can support more browsers. And if not, it would be nice if we can do something with user preference to open FireFox instead of Chrome for users who use FireFox Focus installed for example.

**Comment by richardhinkamp** [comment]
Well... I don't have Firefox installed, only Firefox Focus, so that doesn't make a difference for me. I was expecting that it would open a URL in the default browser, but apparently there is more to it.

**Comment by marcel263** [comment]
I use Firefox Nightly, though it seems like the app is hard-coded to only allow a "safe" pre-defined list of browsers. It launches regular Firefox instead

**Comment by RickAcb** [comment]
I thought to give it a try I don't have any of the browsers provided installed.

The app doesn't allows you to login with DigiD when none of the provided browsers are installed or enabled. 

When I opened CoronaCheck app and tried the DigiD option it crashed, when I reopened the DigiD option it just gives a message "You can log in again later to retrieve your vaccination certificate.".

Other apps like [Berichtenbox](https://play.google.com/store/apps/details?id=nl.rijksoverheid.mbb.pub) just use the default browsers. The banking apps and a lot of other apps that use DigiD (not DigiD app itself) use the default browser and not a forced list of browsers.

I did enable Chrome for the testing purposes and it allows Chrome version 74 on my Android 9 phone. If there is a list of "approved" browsers I think the app should also force the user to update the browsers to a newer versions.

**Comment by milanboers** [comment]
Regarding @RickAcb 's case where no supported browser is installed, I think a lot of confusion can be avoided by improving the error message. Now it shows "you can log in again later", which makes it seem like a temporary server error.

I faced this with the latest Microsoft Edge as the only installed browser.

**Comment by Stephan-P** [comment]
I have de-Googled my Android phone, so I don't have Google Chrome installed. Please update the app to work with any default browser or the DigID app directly.

**Comment by Stephan-P** [comment]
Interestingly, upon tapping the option "ik heb geen digID" the Coronacheck app DOES manage to open https://digID.nl

**Comment by ijansch** [comment]
Apparently we went live on thursday with a 'known safe' configuration. Its' however our intention to support all browsers where the flow works. We'll investigate how we can change the setting and/or increase the list. If you have a good experience with a particular browser and digid in other apps, feel free to list those here so we can collect this feedback.

P.S. 'Mijn Berichtenbox' uses the so-called 'app2app' flow. CoronaCheck currently uses the app2web flow (*), so that we can support both digid app and digid web users.

(*) Technically what happens is an app2web2app2web2app flow 😄 (*): CC opens browser, browser asks if you have digid app, so browser directs to digid app. Digid app after succesful authentication redirects back to web, which in turn redirects back to the coronacheck app.

**Comment by Stephan-P** [comment]
Some alternative webbrowsers to take into consideration:
- Brave
- DuckDuckGo
- Edge
- Samsung Internet Browser
- Vivaldi

I've got D, E and V installed on my device with V set as the default browser.

**Comment by PauluzzS** [comment]
Ideally the app would be agnostic of the browser used. I.e. up to DigID to decide which apps they allow to authenticate through. Setting it in DigID-dependant apps makes them high-maintenance, as a list of browsers will never be exhaustive.

In any case, I use **Edge** as default browser. Also have **Opera, DuckDuckGo** and **Bing** browsers installed. Also have the **DigID app** installed.
The error message "**Retrieval is cancelled** It might be too busy. Please try again later." is giving a completely wrong idea of what is wrong.

**Comment by BartNijland91** [comment]
We will support all browsers that are installed on your device from upcoming 2.1 release.

About the error dialog always saying; `it might be too busy`. Due to time constraints we decided to make one dialog that would fit the most use cases. We will improve upon this later.

**Comment by readefries** [comment]
Thanks for the update @BartNijland91! now the app is also usable when not using Chrome :)

**Comment by BartNijland91** [comment]
@readefries 🙌

**Comment by rctroodt** [comment]
> We will support all browsers that are installed on your device from upcoming 2.1 release.
> 
> About the error dialog always saying; `it might be too busy`. Due to time constraints we decided to make one dialog that would fit the most use cases. We will improve upon this later.

I am using V2.2, Android A51, using Chrome (plus a work profile on my device). No matter what I try in Chrome's settings ( privacy, caching, safe browsing ...), it will never pushback to the CoronaCheck App. When I switch back to the CoronaChecp app manually, it will always give the one and only error code. This means I cannot get the QR code in... 
In the end I managed to get it activated by setting the Standard Browser to Samung's stockbuild version. Never thought I would ever be happy to be able to use this ~browser~ app.

**Comment by nwanko-sk** [comment]
Probleem op mijn telefoon is dat standaard de stock browser wordt geopend (Mi Browser welke ik verder ook niet gebruik) als ik mijn vaccinatiebewijs via DigID wil ophalen. Deze stock browser staat niet in mijn configuratie als standaard ingesteld en werkt niet met DigID. Ik zou dus graag zien dat de standaard ingestelde browser wordt geopend of ik de keuze krijg (ik had oorspronkelijk géén standaard browser ingesteld).

**Comment by readefries** [comment]
Ik heb de stock browser uitgezet (e.g. disabled) waardoor die ook niet kan worden opgestart. Misschien werkt dat ook voor jou.

**Comment by nwanko-sk** [comment]
Disablen van de stock browser lukt niet op deze telefoon. Ik heb wel ondertussen 'dé' workaround ontdekt door vanuit Mi Browser in de browsegeschiedenis de exacte URL te kopiëren (https://tvs.coronacheck.nl/authorize?....) en vervolgens deze in Chrome te openen. Works like a charm! 

@readefries : thanks voor je snelle respons trouwens!

**Comment by readefries** [comment]
Ah, da's jammer. Ik heb een Pixel en kan daar de standaard apps gewoon disablen. Fijn dat je een workaround hebt gevonden, maar dit voelt niet echt als een handige oplossing. Een beetje jammer dat fabrikant dat geblokt heeft :/

@nwanko-sk graag gedaan :)

**Comment by nwanko-sk** [comment]
Niet handig, wel volledig onafhankelijk van welke setting op je telefoon dan ook :-)
