### ISSUE TITLE
"Next" button falls off screen in "make qr code" activity

### ISSUE THREAD

**Issue by marcel263** [minvws/nl-covid19-coronacheck-app-android#30]
### Describe the bug, issue or concern

"Next" button only partially visible, need to scroll down, which might confuse novice users

### To Reproduce
1. Tap "make qr code"
2. Scroll down

### Screenshots
Impossible due to what seems app's security policy 

**Smartphone (please complete the following information):**
 - Device: Samsung device with OneUI 3.1 1080x2400 
 - OS: Android 11
 

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by JJdeGroot** [comment]
This has been done on purpose to make users read all of the text before they continue. If a screen is not large enough to display all text at once, the text is cut off so this indicates that more content is available "after the fold".

There are some user testing sessions planned, if it turns out it confuses people, the design will be updated to make the button visible at all times.

**Comment by marcel263** [comment]
> This has been done on purpose to make users read all of the text before they continue. If a screen is not large enough to display all text at once, the text is cut off so this indicates that more content is available "after the fold".
> 
> There are some user testing sessions planned, if it turns out it confuses people, the design will be updated to make the button visible at all times.

Hello, thank you for your reply.

May I suggest showing a visual indicator that one should scroll down?
