### ISSUE TITLE
Minor UX thing in onboarding: bold text

### ISSUE THREAD

**Issue by EdoPlantinga** [minvws/nl-covid19-coronacheck-app-android#34]
In the android in-app onboarding there is a text highlighting stuff in the privacy statement. The bold text is "er worden geen locatiegegevens **gebruikt of bewaard**". Since the highlighted text is what users see first and "gebruikt of bewaard" does not convey any info by itself, maybe the text can be changed to "er worden **geen locatiegegevens** gebruikt of bewaard".

### Governance
- [x ] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x ] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x ] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by BartNijland91** [comment]
Thanks @EdoPlantinga! Our copywriter has changed this in our copy tool and this change will be present in one of the upcoming releases.
