### ISSUE TITLE
CI: Key store signing errors

### ISSUE THREAD

**Issue by EwoutH** [minvws/nl-covid19-coronacheck-app-android#4]
Currently the [CI fails](https://github.com/minvws/nl-covid19-coronacheck-app-android/runs/1935666198#step:9:955) because something is going wrong with the [key store signing](https://github.com/minvws/nl-covid19-coronacheck-app-android/blob/main/.github/workflows/ci.yml#L44). 

```
FAILURE: Build failed with an exception.
518 actionable tasks: 361 executed, 157 from cache

* What went wrong:
Execution failed for task ':holder:packageTstRelease'.
> A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable
   > com.android.ide.common.signing.KeytoolException: Failed to read key  from store "/home/runner/work/nl-covid19-coronacheck-app-android/nl-covid19-coronacheck-app-android/keystore.jks": null
```

**Comment by EwoutH** [comment]
This issue [still persists](https://github.com/minvws/nl-covid19-coronacheck-app-android/runs/2065312509?check_suite_focus=true#step:9:1270) on the main branch.

**Comment by EwoutH** [comment]
@ijansch @BartNijland91 @SanderVeer @hvisser Could one of you please look into this?

**Comment by hvisser** [comment]
I'm no longer involved in this project. Please don't mention individual members, issues should be monitored by the team.

**Comment by SanderVeer** [comment]
Hi @EwoutH, thanks for your report.
We are aware of this problem, and are working on a proper solution behind the scenes. This repository is a direct copy of our private working repository, with some minor differences. The CI file you mentioned relies on secrets for the generation of the keystore and internal distribution of the apps, which are missing from this public repository. We plan on fixing this in the near future.

**Comment by EwoutH** [comment]
Thanks for your response and explanation Sander! Could you leave the issue open until it's fixed?

**Comment by SanderVeer** [comment]
Fair enough, it has been reopened for the time being.

**Comment by BartNijland91** [comment]
Closing this as this should be fixed now.
