### ISSUE TITLE
Cyclist animation should not respect Android's "remove animations"

### ISSUE THREAD

**Issue by marcel263** [minvws/nl-covid19-coronacheck-app-android#41]
### Describe the bug, issue or concern

Honoring the "remove animations" setting within Android Settings is counterproductive

### To Reproduce
1. Go to Android Settings
2. Go to Accessibility
3 Enable "remove animations" 
4. *note: incidentally, this setting may be hidden within Developer Settings as "animation duration scale"*
5. Generate Dutch QR code

### Expected behavior
 Animated cyclist remains visible so it can serve as a proof of authenticity, even for those normally intolerant toward animations. 

**Smartphone (please complete the following information):**
 - Device: Samsung OneUI 3.1
 
 - App version 2.1.1

### Additional context
People with affected disabilities are at risk of being scapegoated for a perceived attempt to fraud the system. this should not happen.

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by marcel263** [comment]
P.S. start the animation in the center of the screen so that it may still be checked with a tap, flipping the bicycle animation

**Comment by BartNijland91** [comment]
This has been fixed in upcoming release
