### ISSUE TITLE
App uses system time for 14 day validation

### ISSUE THREAD

**Issue by WouterS86** [minvws/nl-covid19-coronacheck-app-android#45]
### Describe the bug, issue or concern

After having 2 vaccins (or 1 with Janssen), the NL QR code only appears after 14 days. There is a clear message that you have to wait x days. When you change your telephone date to +14 days from now, the QR code appears directly. This should not be possible to prevent fraudulent behaviour with the QR code. 

### To Reproduce

1. Get 2 vaccins and load vaccin data into app. 
2. Go to Overview
2. See that the prove 'automatically is valid in x days' / 'wordt automatisch geldig over x dagen'
3. Change the current date of your phone to today+14 days
4. Go back to the corona check app, go to Overview
5. You are now able to click on 'see QR' / 'Bekijk QR'

### Expected behavior
I expect that the countdown from the last vaccin is not using the phone system time. A different method should be used for the countdown of 14 days. 

### Screenshots

**Smartphone (please complete the following information):**
 - Device: Samsung A6
 - OS: Android 10
 - Browser: Chrome
 - Version 2.1.2 (1496)

### Additional context
-

### Governance
- [x ] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x ] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [ x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by ijansch** [comment]
This is intended behaviour. The check that the scanner performs is based on the date that is embedded in the QR, which is digitally signed. Even if you would make the QR visible earlier, it wouldn't yet validate for a scanner. By giving you the QR already when you load your vaccinations, we ensure that the app can remain offline.
