### ISSUE TITLE
login met digid - ophalen is afgebroken (again)

### ISSUE THREAD

**Issue by HvEmm** [minvws/nl-covid19-coronacheck-app-android#47]
### Describe the bug, issue or concern

Na klikken op 'log in met digid' verschijnt de melding 'Het ophalen is afgebroken'.
Dit is eerder een issue geweest, maar het lijkt niet volledig opgelost. 

### To Reproduce
1. app starten
2. Click on 'bewijs toevoegen'
3. Scroll down to 'een vaccinatiebewijs toevoegen.'
4.  press: 'login met digid'
5. See error

### Expected behavior
Ik verwacht dat na het inloggen het vacinatiebewijs wordt opgehaald. 

### Al gewijzigd / geprobeerd:
1 coronacheck-app al diverse malen geheel verwijderd en opnieuw geïnstalleerd
2 telefoontoestel al opnieuw opgestart
3 aanvankelijk geprobeerd met opera-browser (werkte niet). toen firefox geïnstalleerd (werkte niet). toen chrome aangezet. chrome geupdate. chrome werkt ook niet.
4 digid-app geïnstalleerd. daarmee inloggen op bijvoorbeeld digid.nl lukt wel.
5 testbewijs van andere testlocatie opgehaald via ophaalcode (lukt wel)
6 verbinding gewijzigd van wifi naar mobiel-netwerk

**Smartphone (please complete the following information):**
- coronacheckapp: versie 2.1.9 (1649)
 - Device: ZTE A2017G
 - OS: android 8.0.0 (patch 1-4-2019)
 - Browser: Chrome 
 - Version: 92.0.4515.115

### Additional context
Ik wil best logging verstrekken, maar ik heb geen idee hoe ik dat doe. Als aangegeven kan worden hoe ik dat doe, geen probleem.

### Governance
- [v] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [v] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [v] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by nwanko-sk** [comment]
Hier ook een soortgelijk probleem met een Poco F2 Pro telefoon (xiaomi.eu K30Pro software). Bij het openen van DigID voor het vaccinatiebewijs wordt de stock browser automatisch geopend welke niet wordt ondersteund (Mi Browser). Nu heb ik ingesteld dat er géén standaardapp op mijn telefoon is en krijg ik dus altijd de keuze welke browser ik wil gebruiken. Deze keuze krijg ik nu niet. Als ik in de instellingen Chrome als standaard instelt en krijg ik nog steeds dat de Corona app Mi Browser opent. Ook na opnieuw opstarten van de telefoon. Geen enkele andere app op mijn telefoon opende de Mi Browser app.

**Comment by HvEmm** [comment]
Inmiddels 'ontdekt' dat ik idd ook een Mi Browser had (nooit gebruikt, nooit geopend, dus ook geen enkele recht). 
Deze inmiddels verwijderd.
Vervolgens Corona-check-app verwijderd en opnieuw geïnstalleerd.
Telefoon opnieuw opgestart. 
Weer bekende foutmelding.

In issue #27 geef je aan gebruik: https://tvs.coronacheck.nl/authorize?....
Ik kan in mijn browsergeschiedenis (opera, firefox, chrome) geen complete link vinden.
Kan je me verder helpen?

**Comment by nwanko-sk** [comment]
De complete link heb ik uit Mi Browser gehaald
😂 Misschien alsnog opnieuw installeren?

**Comment by HvEmm** [comment]
@ktiniatros : ook in versie 2.2.1 build 1851 gaat het nog steeds fout.

**Comment by HvEmm** [comment]
1 month later: still not working. Anybody home?

**Comment by HvEmm** [comment]
Version 2.3. NEW ERROR. It says foutcode A 210 000 999.

nb. Dit was tested at 22.36 at 20210920 so not during announced work at digid.nl.
