### ISSUE TITLE
Can't open DigiD when phone uses Work Profile

### ISSUE THREAD

**Issue by JolandaVerhoef** [minvws/nl-covid19-coronacheck-app-android#49]
### Describe the bug, issue or concern

Commit 2d461861dac97dd8316f31fd3ef53abe1659b4f3 introduced a regression. With this change, users that have Work Profile set up in their device cannot open their browser anymore to login with DigiD.

When using Work Profile, there's a custom preferred "browser" that lets you choose between the Private and the Work browser. The package name of this "browser" is simply `android` as it's part of the core Android package. 

The commit mentioned above removed the whitelist of browsers, and instead allows all browsers. On a phone with Work Profile installed, this will try to open this generic "browser", using package name `android` which fails and crashes the app.

A simple fix would be to add a filter, which filters out browsers with package name `android`. I'll open a PR with that fix.

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by ijansch** [comment]
Jolanda's fix will be in the next release. I'll close this ticket when the code is in GitHub.

**Comment by ijansch** [comment]
The fix is in the current play store 2.2.1 release.
