### ISSUE TITLE
QR is generated based on date of most recent "last dose" (booster) instead of earliest "last dose"

### ISSUE THREAD

**Issue by Stijn-K** [minvws/nl-covid19-coronacheck-app-android#51]
### Describe the bug, issue or concern

First I received a single dose of pfizer, which was considered my final dose as I had COVID last year. Since this was thus considered my last dose, I received a valid QR in the app. This week, because several reasons I opted to also get the 2nd shot of pfizer. Both shots are now considered the last dose of my vaccination according to the app ("is this the last dose of your vaccination? **yes**). The app now takes the most recent dose for the QR and now I'm unable to generate a QR.
My first dose was on the 28th of june, and the 2nd dose was on the 4th of august.

E.g. 

### To Reproduce
1. Get COVID and recover
2. opt for a single dose of pfizer
3. load vaccine data and enjoy your valid QR
4. opt for a second dose of pfizer because reasons
5. reload vaccine data and you will have to wait 14 days to enjoy your valid QR again

### Expected behavior
Since I received my actual last dose already on june 28th, I should be able to generate a valid QR, regardless of any (booster) shots received after.

**Smartphone (please complete the following information):**
 - Device: OnePlus 7T
 - OS: Android 11
 - Browser: Chrome
 - Version: 92.0.4515.131

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by ijansch** [comment]
Thanks. We are aware of this issue. It’s not android specific but I’ll leave this issue open until we release the fix. 

The fix will be that in this case you will be able to also show the previous QR. Only generating it based on the original last dose would not work in some countries who might apply business rules for boosters.
