### ISSUE TITLE
No Dutch vaccination proof, when all data is correct.

### ISSUE THREAD

**Issue by tomsonnemans** [minvws/nl-covid19-coronacheck-app-android#52]
### Describe the bug, issue or concern

Received a Pfizer vaccination, and needed to get a second vaccination. Due to an earlier infection with covid, I than got notified i only had to get one vaccine. So canceled the second appointment.
I can only create an international certificate, not a national one, even though the GGD filled a new questionnaire, which stated i have had COVID and only needed 1 vaccination.
The questionnaire is filled 14th of June. And we are waiting for more than 2 months now, to get it fixed / updated.

### To Reproduce
1. Have a postitive test;
2. Get 1 of 2 vaccinations;
3. Cancel the 2nd because it is not needed anymore;
4. Get doses 1/2 adjusted by filling in a new questionnaire;
5. Retrieve vaccination proof in app / website or anywhere;
6. Get only an international one.

### Expected behavior
We should get a valid Dutch vaccination proof.

**Desktop & Smartphone (please complete the following information):**
 - OS: iOS & Android & Website

### Governance
- [ x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [ x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [ x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by Chantalcg** [comment]
Thanks for reaching out. You should indeed get an international QR if CoronaCheck receives your data correct from the GGD. You can contact them again via 0800-5090 and inform them about this. If this is not working please contact the CoronaCheck helpdesk. You can reach them at 0800-1421 (Monday to Sunday from 8 am - 8 pm) or via helpdesk@coronacheck.nl.

**Comment by GinPentatonic** [comment]
Hi Ivo Jansch,

Is your problem solved? That's great. How did you solve it? 
We have the same problem but no one seems to be able to correct the data in the coronacheck app. 

Thanks for your reply.

**Comment by tomsonnemans** [comment]
@GinPentatonic, we solved it by contacting th GGD and requesting an emergency procedure (spoed procedure). Because we had plans to leave the country. Within 48 hours we got a letter via mail with a QR code and an activation number to generate the QR in the app.

Hope this will help you out.
