### ISSUE TITLE
'Ziekteverwekker / Disease' text value in details international QR-code wrong

### ISSUE THREAD

**Issue by KTMAdventureRider** [minvws/nl-covid19-coronacheck-app-android#54]
### Describe the bug, issue or concern

When I choose Main screen - Internationaal - select Button BEKIJK QR) and then select the question mark at the top right in the international QR code screen (the screen with the QR code and the animations), the text value at the label 'Ziekteverwekker / Disease targeted:' is not correct. The text value states '**Ziekteverwekker:**' Comparing this with the paper version (papieren bewijs), generated through https://coronacheck.nl/nl/print/ I noticed the difference. There the text value states '**COVID-19**', which is correct, I assume. 

### To Reproduce
1. Go to main screen 'Mijn bewijzen'
2. Select menu 'Internationaal'
2. Click on button 'BEKIJK QR'
3. Click on question mark symbol in right top corner 
4. See error under 'Ziekteverwekker / Disease targeted:' where the text value states '**Ziekteverwekker:**'

### Expected behavior
The expected behavior should be that the text value should display '**COVID-19**' instead of 'Ziekteverwekker:'

### Screenshots
![coronacheckapp_bug](https://user-images.githubusercontent.com/88939392/129452915-aa076a46-2a6e-45eb-929f-6b93ba9e999e.jpg)

**Smartphone (please complete the following information):**
 - Device: [OnePlus 8T]
 - OS: [Android 11]
 - Browser [Chrome]
 - Version [92.0.4515.131]
 - Coronacheck app version 2.2.1 (1851)

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by jpelgrom** [comment]
This seems to be a case of simply using the wrong string, I'll submit a PR to fix this shortly

**Comment by ijansch** [comment]
This was fixed, thanks again!
