### ISSUE TITLE
DIGI_D_REDIRECT_URI change doesn't work with some browsers

### ISSUE THREAD

**Issue by obfusk** [minvws/nl-covid19-coronacheck-app-android#62]
### Describe the bug, issue or concern

The change in `DIGI_D_REDIRECT_URI` (from `coronacheck://auth/login` to `https://coronacheck.nl/app/auth`) doesn't work with some browsers (like the lineageOS stock browser) that don't support opening http(s) links in other applications.

Clicking on the "open in app" button in the web page just opens the link in the same browser window, making it impossible to finish adding the certificate after the DigiD login was successful.

Changing the "open supported links" setting for CoronaCheck to "allow app to open supported links" doesn't help.

The old non-http(s) link used in older versions of CoronaCheck works fine.

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by ijansch** [comment]
This was fixed by having the page that these browsers open redirect to the old schema.
