### ISSUE TITLE
Geen QR code (indien corona + 1 vaccinatie)

### ISSUE THREAD

**Issue by GinPentatonic** [minvws/nl-covid19-coronacheck-app-android#65]
**Problem: geen QR code (indien corona + 1 vaccinatie)**

Indien je corona gehad hebt zou je met 1 vaccinatie voldoende bescherming moeten hebben om een QR code te krijgen. 
Bij die vaccinatie moet dan aangevinkt worden dat er een eerdere besmetting was zodat in de QR code ‘1 van 1 vaccinaties’ komt te staan. 
Indien bovenstaande het geval is: hoe (en wie/welke instantie) kan dit aanpassen indien er toch geen QR code verkregen wordt omdat er ‘1 van 2 vaccinaties’ staat. 
Bij huisarts, GGD, huisartsenvereniging, RIVM etc komen we niet verder. Dit zijn de logische contactpunten, maar naar mijn idee is het data verwerkingsprobleem en bij hen komen we niet verder. Iedereen doet z'n best en is behulpzaam, maar nergens komen we verder omdat niemand iets kan aanpassen in zijn/haar systeem (en iedereen zegt dat een andere persoon of instantie dat wel kan/moet kunnen). 

Bij wie of welke instantie kunnen we terecht die wel dieper in de database kan om dit (met terugwerkende kracht) aan te passen?

**Comment by janmg** [comment]
Ik heb geen corona gehad, maar wel het Janssen vaccine en CoronaCheck geeft "Geen vaccinatie beschikbaar), terwijl GGD via http://www.coronavaccinatie-afspraak.nl/ wel correct is en ik het vinkje, delen met RIVM toch echt heb aangevinkt.

Het moet gewoon een probleem zijn in de database koppeling tussen RIVM and GGD.  

https://www.rijksoverheid.nl/onderwerpen/coronavirus-covid-19/coronabewijs/vaccinatiebewijs 
_CoronaCheck kan uw vaccinatie met Janssen niet ophalen 
Het komt voor dat de vaccinatiegegevens van de GGD niet goed worden doorgegeven aan CoronaCheck. Hierdoor worden de gegevens niet zichtbaar in CoronaCheck. U kunt hiervoor contact opnemen met de de GGD, via 0800-5090. Zij kunnen kijken wat er aan de hand is en uw gegevens aanpassen als dat nodig is._ 

Bellen heeft echt totaal geen zin gehad. Ik heb nu een papieren QR code per post aangevraagd, via een geautomatiseerd systeem, maar dan moet je maar afwachten of je hem krijgt. Ik ga er vanuit dat mijn verzoek in een putje verdwijnt en er niks aan gedaan wordt.
https://eenvandaag.avrotros.nl/item/wel-gevaccineerd-geen-qr-code-bij-tientallen-gedupeerden-kan-het-deuntje-van-de-ggd-helpdesk-inmiddels-dromen/ 

Ik ben bang dat ik een kortgeding moet aanspannen om uberhaupt aandacht voor dit probleem te krijgen. Voor reizen binnen Europa is het behoorlijk zuur om weer bij de douane te worden tegengehouden, want daar verwachten ze gewoon dat de europese afspraken worden nageleefd.
