### ISSUE TITLE
Total number of doses is not shown correctly in international vaccination after booster (3rd) vaccination

### ISSUE THREAD

**Issue by joro75** [minvws/nl-covid19-coronacheck-app-android#78]
### Describe the bug, issue or concern
I did receive a 3rd vaccination because of a severe immune system disorder. This is officially not a booster vaccination, however can be seen equally regarding the problem I observed.
I thus have a third vaccination, after my earlier two vaccinations. In the CoronaCheck app, on the tab that is showing the international vaccination certificates, the vaccinations are shown as:
* Dose 3/3
* Dose 2/2
* Dose 1/2

The total dose counter for dose 1 and dose 2 are thus shown incorrectly, as I would expect them to be shown as:
* Dose 3/3
* Dose 2/3
* Dose 1/3

Also on the QR code view, QR code selector is showing 'Dose 1/2' and 'Dose 2/2' where I would expect it to show: 'Dose 1/3' and 'Dose 2/3'. The selector is correctly showing 'Dose 3/3'.

Also see the attached screenshots

### To Reproduce
Steps to reproduce the behaviour:
1. Start the CoronaCheck app
2. Click on 'International' tab
3. See first screenshot
4. Click on the 'View QR Codes' button
5. See the second screenshot

### Expected behaviour
I would expect that the total number of doses (3 in my case at this moment), is shown correctly when it is shown in 'Dose x/y' style strings.

### Screenshots
The overview of the vaccinations on the 'International' tab.
![image](https://user-images.githubusercontent.com/16726172/142768136-b7734656-59a0-41a6-b8f0-3f762cde1403.png)

The QR code selector. Notice the three dots, and the still enabled 'go to right' button.
![image](https://user-images.githubusercontent.com/16726172/142768067-a2a575f6-6f75-4bc9-a9ff-de09be3813fe.png)

**Smartphone (please complete the following information):**
 - Device: Samsung A51
 - OS: Android 11
 - Browser: Chrome
 - Chrome Version: 96.0.4664.45
 - CoronaCheck version: 2.5 (2753)

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by joro75** [comment]
I did provide a PR (#79) to fix the problem on the selector of the International QR Code view. 

I also checked on how to resolve this problem on the overview of the received vaccinations on the 'International' tab, however that seems to be more complicated. The 'Dose x/y' seems to be generated in the MyOverViewGreenCardAdapterUtil.kt file by the `getCurrentDosesString` lambda function. The total number of doses is however not present in the `setEuVaccinationOrigin` function. 
A suggestion is to provide an additional 'cardCount' parameter to `setEuVaccinationOrigin`.

**Comment by ijansch** [comment]
The ‘/2’ part is intended to indicate how many vaccinations a person would need. The system has no way of telling that a person needs 3 so at the 2nd jab it bases the 2 purely on the amount of doses normally required for that vaccine type. You could retroactively correct the 2/2 once the 3d shot is applied, but each Qr should be usable independently and a 2/3 would mean an incomplete vaccination (which isn’t always true).

**Comment by joro75** [comment]
Thanks for the explanation. Based on your explanation I now can understand why it is still showing the '/2' part.
I hope that you also understand that I (as a normal end-user of the app) am confused when I see 2/2 and 3/3. It is just confusing and seems to be a bug, without the explanation that you provided.

Browsing through the code, I did realize that there are a lot of cases and different situations that should be taken into account. 
I'm thus not an expert regarding all these cases, however I still believe that if 3 QR codes are present every end-user would assume that 'Dose x/3' is shown. 

That is just my opinion. At this moment I do not have a good suggestion on how to clearify this. Thanks again for the explanation. I will close the issue.
