### ISSUE TITLE
CoronaCheck app doesn't start on Android 12

### ISSUE THREAD

**Issue by RoelD** [minvws/nl-covid19-coronacheck-app-android#87]
### Describe the bug, issue or concern

When i press the icon to launch the app, the splash screen with logo comes up. Then it stays on that screen for a couple minutes.
Then the app just closes. No force close dialog or anything. The same happens to the Scanner for CoronaCheck app.

I have added a screenrecoding of the bug. in this case, a force close dialog does appear however.
I have wiped cache and data multiple times, and all apps are up to date.

https://user-images.githubusercontent.com/7955675/150752300-ab275940-c51b-483d-b833-5f79e71741fb.mp4

The DigiD app works without any problems.

** Possible fix
I notice that the targeted SDK version of this app is 30. Android 12 uses 31. Is the app not compatible yet?

 - Device: OnePlus 8T
 - OS: Android 12
 - Browser : Chrome 
 - Version: 96.0.4664.104

### Governance
- [ x ] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [ x ] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [ x ] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.

com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by RoelD** [comment]
i saw the latest PR has targeted SDK updated to 31. However the app version was increased to 2.7.1.
I have just downloaded the 2.7.1 app from the Play Store and checked the build.gradle in the app. The SDK version is still 30.

**Comment by BartNijland91** [comment]
Hey @RoelD ,

Is this 2.7.1? And did you send the crash report? I can't seem to find one for a OnePlus 8T on Android 12.

**Comment by RoelD** [comment]
Sounds plausible.
is the used encryption that different from DigiD? That app runs fine.

**Comment by BartNijland91** [comment]
Don't know if/what kind of encryption DigiD uses, that's a different app. I'm closing this ticket since we do not support the use of custom roms. A contribution to make it work on your custom rom is more than welcome of course!
