### ISSUE TITLE
Deeplinking met feedback

### ISSUE THREAD

**Issue by conceptos-nl** [minvws/nl-covid19-coronacheck-app-android#95]
Het is zonder problemen gelukt de app te compileren in Android Studio en deze op mijn emulator te draaien. Echter krijg ik bij elke scan dat de QR code onjuist is. Komt dit omdat dit geen productie versie is?

Mijn doel is om te kijken hoe er in combinatie met deeplinken een nog beter connectie gelegd kan worden. Ik probeer een concept te maken waarbij middels 1 stand alone apparaat ook visuele feedback naar de persoon gegeven wordt doormiddel van een lamp aan de voorzijde van een apparaat die groen kleurt als de volledige stappen goed zijn doorlopen. Echter vanuit de Verifier is er geen event dat aangeeft of de scan succesvol is geweest, op die manier kan een externe applicatie hier niet op reageren.

Het zou een zeer waardevolle optie zijn als het resultaat van de scan ook teruggeven wordt in de deeplink.

**Comment by BartNijland91** [comment]
De app heeft verschillende build flavors, ik denk dat je een van de twee apps (holder / verifier) in een andere flavor dan prod draait.

**Comment by conceptos-nl** [comment]
Bart,

Dank voor je reactie, ik dacht dat ik deze goed had staan maar hij stond nog op debug. Ik kan hem nu succesvol compileren en heb een versie gebouwd waarmee ook verlichting wordt aangestuurd op de scanner die ik gebruik.

snel-toegang.nl
