### ISSUE TITLE
App fails to start when VPN is active

### ISSUE THREAD

**Issue by fschaap** [minvws/nl-covid19-coronacheck-app-android#96]
### Describe the bug, issue or concern

When the CoronaCheck app has not been used for a while, it wants make a network connection when starting up. If my VPN is active, this network connection fails and I get the error "Maak verbinding met het internet. Om toegang to je QR-codes te houden heb je internet nodig. Maak nu verbinding." The dialog has the options "Sluiten" and "Probeer opnieuw". Neither option does anything. The dialog will flicker intermittently. This is totally reproducable on my phone.

Every other app on my phone works just fine and can use network connections via the VPN. Only the CoronaCheck app fails to work with the VPN.

It doesn't matter if the underlying connection is 4G or WiFi, if the VPN is active, the CoronaCheck app fails to work. When I turn off the VPN and start the CoronaCheck app again, it works just fine and it doesn't matter if the network connection is 4G or WiFi.

Please fix the app so it properly detects a network connection even when using a VPN.

### To Reproduce
1. Enable VPN
2. I tested with OpenVPN and Mullvad client apps from the Play Store. I used both Wireguard and OpenVPN protocols. I tested with a commercial VPN (Mullvad) and a private VPN.
3. Make sure CoronaCheck app has not been used for a certain period so that it wants to validate via a network connection when starting up
4. Launch the CoronaCheck app

### Expected behavior
I expect the CoronaCheck app to launch and work as intended even when using a VPN.

### Screenshots
The app prevents taking screenshots, so there are none.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: OnePlus 3T
 - OS: OxygenOS 9.0.6 (Android 9)
 - Browser: Firefox Focus
 - Version: 96.3.1

### Additional context
-

### Governance
- [ ] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [ ] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [ ] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by BartNijland91** [comment]
I tried with ExpressVPN in the current production app (2.8.1) and it seems to work for me. Can you check if fetching your vaccinations again fails as well when your VPN is enabled?

**Comment by fschaap** [comment]
Situation unchanged. Enabling a VPN, any VPN, prevents the app from fetching/updating the vaccination data.

**Comment by BartNijland91** [comment]
What error code/screen do you get when fetching your vaccinations?

**Comment by BartNijland91** [comment]
I mean when you get your vaccinations from DigiD again.

**Comment by fschaap** [comment]
I don't need to identify with DigiD again. I just opened the CoronaCheck app without a VPN active on my phone. The app just connects, validates and give me access to my QR-codes again.

It really only is the 10-day (?) re-validation that fails with an active VPN.

**Comment by BartNijland91** [comment]
I understand, I'm trying to pinpoint the issue. Can you try fetching your vaccinations with Digi-D with the VPN enabled, and let me know what the outcome of that is?

**Comment by fschaap** [comment]
From the CoronaCheck app, with VPN enabled:
1. I am redirected to the DigiD login page
2. I choose to login with my DigiD app "on this phone"
3. authentication succeeds
4. I am redirected back to the CoronaCheck app
5. Error message in the CoronaCheck app: "Sorry, er gaat iets mis. Het is niet gelukt de server te bereiken. Wil je controleren of je verbinding met het internet hebt? [Sluiten] [Probeer opnieuw]"

Without the VPN, refreshing the vaccinations works fine.

**Comment by fschaap** [comment]
From the CoronaCheck app, with VPN enabled:
1. I am redirected to the DigiD login page
2. I choose to login with my DigiD app "on this phone"
3. authentication succeeds
4. I am redirected back to the CoronaCheck app
5. Error message in the CoronaCheck app: "Sorry, er gaat iets mis. Het is niet gelukt de server te bereiken. Wil je controleren of je verbinding met het internet hebt? [Sluiten] [Probeer opnieuw]"

Without the VPN, refreshing the vaccinations works fine.

**Comment by nicktencate** [comment]
I have tried several VPN services and discovered that many nodes are blocked due to abuse of the CoronaCheck eco system. Unfortunately there is nothing we can do about this.

If you have issues reaching us from a certain VPN provider, you can ask the the VPN provider to contact us at security@coronacheck.nl to discuss the possibility of delisting the affected node.
